# Description: this file contains test cases generated by the copilot.
import unittest
import fizzbuzz


class TestFizzBuzz(unittest.TestCase):
    # generate four test case methods for the fizzbuzz program.
    # 1. test_fizz_buzz
    # 2. test_fizz
    # 3. test_buzz
    # 4. test_number

    def test_fizz_buzz(self):
        self.assertEqual(fizzbuzz.fiz_buz_func(15), 'FizzBuzz')

    def test_fizz(self):
        self.assertEqual(fizzbuzz.fiz_buz_func(3), 'Fizz')

    def test_buzz(self):
        self.assertEqual(fizzbuzz.fiz_buz_func(5), 'Buzz')

    def test_number(self):
        self.assertEqual(fizzbuzz.fiz_buz_func(7), 7)


if __name__ == '__main__':
    unittest.main()
